Use nested environment variables
Use environment variables within environment variable in order to make
it easier for the user to change e.g. the name of the JAR file while
keeping the JAVA options fixed.

While working on environment variables, rename `myname` to `INAME` and
`game` to `GAME`.

Resolves #2 .

diff --git a/minecraftd.sh.in b/minecraftd.sh.in
--- a/minecraftd.sh.in
+++ b/minecraftd.sh.in
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-# The actual program name
-declare -r myname="@MYNAME@"
-declare -r game="@GAME@"
+# The actual program name (name of the interface)
+declare -r INAME="@INAME@"
+declare -r GAME="@GAME@"
 
 # General rule for the variable-naming-schema:
 # Variables in capital letters may be passed through the command line others not.
@@ -33,7 +33,7 @@ declare -r game="@GAME@"
 [[ -n "${GAME_COMMAND_DUMP}" ]] && declare -r GAME_COMMAND_DUMP=${GAME_COMMAND_DUMP} || GAME_COMMAND_DUMP="@GAME_COMMAND_DUMP@"
 
 # Variables passed over the command line will always override the one from a config file
-source /etc/conf.d/"${game}" 2>/dev/null || >&2 echo "Could not source /etc/conf.d/${game}"
+source /etc/conf.d/"${GAME}" 2>/dev/null || >&2 echo "Could not source /etc/conf.d/${GAME}"
 
 # Preserve the content of IDLE_SERVER without making it readonly
 [[ -n ${tmp_IDLE_SERVER} ]] && IDLE_SERVER=${tmp_IDLE_SERVER}
@@ -133,7 +133,7 @@ idle_server_daemon() {
 				no_player=$(( no_player + CHECK_PLAYER_TIME ))
 				# Stop the game server if no player was active for at least ${IDLE_IF_TIME}
 				if [[ "${no_player}" -ge "${IDLE_IF_TIME}" ]]; then
-					IDLE_SERVER="false" ${myname} stop
+					IDLE_SERVER="false" ${INAME} stop
 					# Wait for game server to go down
 					for i in {1..100}; do
 						socket_has_session "${SESSION_NAME}" || break
@@ -146,7 +146,7 @@ idle_server_daemon() {
 					echo -n "Netcat: "
 					${NETCAT_CMD} -v -l -p ${GAME_PORT} 2>&1 | (grep -m1 -i "connect" && pkill -P $$ ${NETCAT_CMD}) || true
 					echo "Netcat caught a connection. The server is coming up again..."
-					IDLE_SERVER="false" ${myname} start
+					IDLE_SERVER="false" ${INAME} start
 				fi
 			else
 				# Reset timer since there is an active player on the server
@@ -159,7 +159,7 @@ idle_server_daemon() {
 			echo -n "Netcat: "
 			${NETCAT_CMD} -v -l -p ${GAME_PORT} 2>&1 | (grep -m1 -i "connect" && pkill -P $$ ${NETCAT_CMD}) || true
 			echo "Netcat caught a connection. The server is coming up again..."
-			IDLE_SERVER="false" ${myname} start
+			IDLE_SERVER="false" ${INAME} start
 		fi
 	done
 }
@@ -220,14 +220,14 @@ server_start() {
 			for i in {1..100}; do
 				sleep 0.1
 				if ! socket_has_session "${IDLE_SESSION_NAME}"; then
-					${SUDO_CMD} tmux -L "${SESSION_NAME}" new-session -s "${IDLE_SESSION_NAME}" -d "${myname} idle_server_daemon"
+					${SUDO_CMD} tmux -L "${SESSION_NAME}" new-session -s "${IDLE_SESSION_NAME}" -d "${INAME} idle_server_daemon"
 					break
 				fi
 				[[ $i -eq 100 ]] && echo -e "An \e[39;1merror\e[0m occurred while trying to reset the idle_server!"
 			done
 		else
 			echo -en "Starting idle server daemon..."
-			${SUDO_CMD} tmux -L "${SESSION_NAME}" new-session -s "${IDLE_SESSION_NAME}" -d "${myname} idle_server_daemon"
+			${SUDO_CMD} tmux -L "${SESSION_NAME}" new-session -s "${IDLE_SESSION_NAME}" -d "${INAME} idle_server_daemon"
 			echo -e "\e[39;1m done\e[0m"
 		fi
 	fi
@@ -480,17 +480,17 @@ socket_session_is_alive() {
 # Help function, no arguments required
 help() {
 	cat <<-EOF
-	This script was designed to easily control any ${game} server. Almost any parameter for a given
-	${game} server derivative can be changed by editing the variables in the configuration file.
+	This script was designed to easily control any ${GAME} server. Almost any parameter for a given
+	${GAME} server derivative can be changed by editing the variables in the configuration file.
 
-	Usage: ${myname} {start|stop|restart|status|backup|restore|command <command>|console}
-	    start                Start the ${game} server
-	    stop                 Stop the ${game} server
-	    restart              Restart the ${game} server
+	Usage: ${INAME} {start|stop|restart|status|backup|restore|command <command>|console}
+	    start                Start the ${GAME} server
+	    stop                 Stop the ${GAME} server
+	    restart              Restart the ${GAME} server
 	    status               Print some status information
 	    backup               Backup the world data
 	    restore [filename]   Restore the world data from a backup
-	    command <command>    Run the given command at the ${game} server console
+	    command <command>    Run the given command at the ${GAME} server console
 	    console              Enter the server console through a tmux session
 
 	Copyright (c) Gordian Edenhofer <gordian.edenhofer@gmail.com>
