Multiple instances + systemd sandboxing support
Currently the management scripts allow for only a single instance of the minecraft server to be run, but it's actually not hard at all to support multiple instances. This commit makes the following changes:

  - Adds a new systemd service file, `minecraftd@.service`, which is an instantiated variant that overrides `SERVER_ROOT` and `SESSION_NAME`
  - Modifies `minecraftd.sh` to support overriding the path to the environment file via the `CONFIG_PATH` environment variable. The instantiated variant of the systemd unit also uses the environment file `/etc/@GAME@/%i` if it exists.
  - Instantiated versions of the minecraftd-backup service and timer.
  - Enables systemd's sandboxing at the instance level. A running server instance cannot modify backups or data/config/etc. files for other worlds.

The intended use case for this change is fairly common: using the same package to run multiple instances of a minecraft server on a single host. This would commonly be seen with, for example, multi-server bungeecord deployments.

Documentation is included.

Miscellaneous improvements:

  - Fixed a few locations in the startup script that did not have `${SUDO_CMD}`
  - Added a `.gitignore` file for generated files

Supporting changes:

  - The path to the tmux socket has been changed. It now lives under `/run/@GAME@/tmux`. This allows it to be bind mounted inside the per-instance namespace.

Testing performed:

  - Clean install, new server - single
  - Clean install, new servers - instantiated
  - Clean install backup - single
  - Clean install backup - instantiated
  - Production system, upgrade - instantiated

diff --git a/minecraftd.sh.in b/minecraftd.sh.in
--- a/minecraftd.sh.in
+++ b/minecraftd.sh.in
@@ -9,14 +9,16 @@ declare -r GAME="@GAME@"
 # Avoid altering any of those later in the code since they may be readonly (IDLE_SERVER is an exception!)
 
 # You may use this script for any game server of your choice, just alter the config file
-[[ -n "${SERVER_ROOT}" ]]  && declare -r SERVER_ROOT=${SERVER_ROOT}   || SERVER_ROOT="@SERVER_ROOT@"
-[[ -n "${BACKUP_DEST}" ]]  && declare -r BACKUP_DEST=${BACKUP_DEST}   || BACKUP_DEST="@BACKUP_DEST@"
-[[ -n "${BACKUP_PATHS}" ]] && declare -r BACKUP_PATHS=${BACKUP_PATHS} || BACKUP_PATHS="@BACKUP_PATHS@"
-[[ -n "${BACKUP_FLAGS}" ]] && declare -r BACKUP_FLAGS=${BACKUP_FLAGS} || BACKUP_FLAGS="@BACKUP_FLAGS@"
-[[ -n "${KEEP_BACKUPS}" ]] && declare -r KEEP_BACKUPS=${KEEP_BACKUPS} || KEEP_BACKUPS="@KEEP_BACKUPS@"
-[[ -n "${GAME_USER}" ]]    && declare -r GAME_USER=${GAME_USER}       || GAME_USER="@GAME_USER@"
-[[ -n "${MAIN_EXECUTABLE}" ]] && declare -r MAIN_EXECUTABLE=${MAIN_EXECUTABLE} || MAIN_EXECUTABLE="@MAIN_EXECUTABLE@"
-[[ -n "${SESSION_NAME}" ]] && declare -r SESSION_NAME=${SESSION_NAME} || SESSION_NAME="@SESSION_NAME@"
+[[ -n "${SESSION_NAME}" ]]    && declare -r session_name_overridden=true       || declare -r session_name_overridden=false
+[[ -n "${SERVER_ROOT}" ]]     && declare -r SERVER_ROOT=${SERVER_ROOT}         || SERVER_ROOT="@SERVER_ROOT@"
+[[ -n "${CONFIG_PATH}" ]]     && declare -r CONFIG_PATH=${CONFIG_PATH}         || CONFIG_PATH="@CONFIG_PATH@"
+[[ -n "${BACKUP_DEST}" ]]     && declare -r BACKUP_DEST=${BACKUP_DEST}         || BACKUP_DEST="@BACKUP_DEST@"
+[[ -n "${BACKUP_PATHS}" ]]    && declare -r BACKUP_PATHS=${BACKUP_PATHS}       || BACKUP_PATHS="@BACKUP_PATHS@"
+[[ -n "${BACKUP_FLAGS}" ]]    && declare -r BACKUP_FLAGS=${BACKUP_FLAGS}       || BACKUP_FLAGS="@BACKUP_FLAGS@"
+[[ -n "${KEEP_BACKUPS}" ]]    && declare -r KEEP_BACKUPS=${KEEP_BACKUPS}       || KEEP_BACKUPS="@KEEP_BACKUPS@"
+[[ -n "${GAME_USER}" ]]       && declare -r GAME_USER=${GAME_USER}             || GAME_USER="@GAME_USER@"
+[[ -n "${MAIN_EXECUTABLE}" ]] && declare -r MAIN_EXECUTABLE=${MAIN_EXECUTABLE} || MAIN_EXECUTABLE="@MAIN_EXECUTABLE_ABSOLUTE@"
+[[ -n "${SESSION_NAME}" ]]    && declare -r SESSION_NAME=${SESSION_NAME}       || SESSION_NAME="@SESSION_NAME@"
 
 # Command and parameter declaration with which to start the server
 [[ -n "${SERVER_START_CMD}" ]] && declare -r SERVER_START_CMD=${SERVER_START_CMD} || SERVER_START_CMD="@SERVER_START_CMD@"
@@ -33,7 +35,9 @@ declare -r GAME="@GAME@"
 [[ -n "${GAME_COMMAND_DUMP}" ]] && declare -r GAME_COMMAND_DUMP=${GAME_COMMAND_DUMP} || GAME_COMMAND_DUMP="@GAME_COMMAND_DUMP@"
 
 # Variables passed over the command line will always override the one from a config file
-source /etc/conf.d/"${GAME}" 2>/dev/null || >&2 echo "Could not source /etc/conf.d/${GAME}"
+if test -r "${CONFIG_PATH}"; then
+	source "${CONFIG_PATH}" || (echo "Could not source ${CONFIG_PATH}" >&2)
+fi
 
 # Preserve the content of IDLE_SERVER without making it readonly
 [[ -n ${tmp_IDLE_SERVER} ]] && IDLE_SERVER=${tmp_IDLE_SERVER}
@@ -51,6 +55,23 @@ if [[ "$(whoami)" == "${GAME_USER}" ]]; then
 	SUDO_CMD=""
 else
 	SUDO_CMD="sudo -u ${GAME_USER}"
+fi
+
+# We use an alternate tmux socket directory because tmux's default socket
+# directory includes the uid. The systemd sandboxing uses a private /tmp,
+# so to expose the tmux socket directory to the host we need to change to
+# a socket path that uses the user id.
+GAME_USER_UID=$(${SUDO_CMD} id -u)
+LEGACY_TMUX_SOCKET_PATH="/tmp/tmux-${GAME_USER_UID}/${SESSION_NAME}"
+TMUX_SOCKET_PATH="@TMUX_SOCKET_DIR@/${SESSION_NAME}"
+# Look for the old socket path prior to version upgrade. If we find it,
+# and there's nothing running on the new path yet, use the old path so we
+# can still safely stop the old server, send commands, etc.
+if [[ -S "${LEGACY_TMUX_SOCKET_PATH}" && ! -S "${TMUX_SOCKET_PATH}" ]]; then
+	TMUX_CMD="${SUDO_CMD} tmux -S ${LEGACY_TMUX_SOCKET_PATH}"
+else
+	test -d `dirname "${TMUX_SOCKET_PATH}"` || mkdir -p `dirname "${TMUX_SOCKET_PATH}"`
+	TMUX_CMD="${SUDO_CMD} tmux -S ${TMUX_SOCKET_PATH}"
 fi
 
 # Choose which flavor of netcat is to be used
@@ -71,17 +92,17 @@ fi
 # Pipe any given argument to the game server console,
 # sleep for $sleep_time and return its output if $return_stdout is set
 game_command() {
-	${SUDO_CMD} tmux -L "${SESSION_NAME}" wait-for -L "command_lock"
+	${TMUX_CMD} wait-for -L "command_lock"
 	if [[ -z "${return_stdout:-}" ]]; then
-		${SUDO_CMD} tmux -L "${SESSION_NAME}" send-keys -t "${SESSION_NAME}":0.0 "$*" Enter
+		${TMUX_CMD} send-keys -t "${SESSION_NAME}":0.0 "$*" Enter
 	else
-		${SUDO_CMD} tmux -L "${SESSION_NAME}" pipe-pane -t "${SESSION_NAME}":0.0 "cat > ${GAME_COMMAND_DUMP}"
-		${SUDO_CMD} tmux -L "${SESSION_NAME}" send-keys -t "${SESSION_NAME}":0.0 "$*" Enter
+		${TMUX_CMD} pipe-pane -t "${SESSION_NAME}":0.0 "cat > ${GAME_COMMAND_DUMP}"
+		${TMUX_CMD} send-keys -t "${SESSION_NAME}":0.0 "$*" Enter
 		sleep "${sleep_time:-0.3}"
-		${SUDO_CMD} tmux -L "${SESSION_NAME}" pipe-pane -t "${SESSION_NAME}":0.0
+		${TMUX_CMD} pipe-pane -t "${SESSION_NAME}":0.0
 		${SUDO_CMD} cat "${GAME_COMMAND_DUMP}"
 	fi
-	${SUDO_CMD} tmux -L "${SESSION_NAME}" wait-for -U "command_lock"
+	${TMUX_CMD} wait-for -U "command_lock"
 }
 
 # Check whether there are player on the server through list
@@ -125,7 +146,7 @@ idle_server_daemon() {
 		if socket_has_session "${SESSION_NAME}"; then
 			# Game server is up and running
 			# Check for active player
-			if [[ -n "$(tmux -L "${SESSION_NAME}" list-clients -t "${SESSION_NAME}":0.0 2> /dev/null)" ]]; then
+			if [[ -n "$(${TMUX_CMD} list-clients -t "${SESSION_NAME}":0.0 2> /dev/null)" ]]; then
 				# An administrator is connected to the console, pause player checking
 				echo "An admin is connected to the console. Pause player checking."
 			elif SUDO_CMD="" is_player_online; then
@@ -175,12 +196,12 @@ server_start() {
 		# Use a plain file as command buffers for the server startup and switch to a FIFO pipe later
 		${SUDO_CMD} touch "${GAME_COMMAND_DUMP}"
 		# Ensure pipe-pine is started before the server itself by splitting the session creation and server startup
-		${SUDO_CMD} tmux -L "${SESSION_NAME}" new-session -s "${SESSION_NAME}" -c "${SERVER_ROOT}" -d /bin/bash
+		${TMUX_CMD} new-session -s "${SESSION_NAME}" -c "${SERVER_ROOT}" -d /bin/bash
 		# Mimic GNU screen and allow for both C-a and C-b as prefix
-		${SUDO_CMD} tmux -L "${SESSION_NAME}" set -g prefix2 C-a
-		${SUDO_CMD} tmux -L "${SESSION_NAME}" wait-for -L "command_lock"
-		${SUDO_CMD} tmux -L "${SESSION_NAME}" pipe-pane -t "${SESSION_NAME}":0.0 "cat > ${GAME_COMMAND_DUMP}"
-		${SUDO_CMD} tmux -L "${SESSION_NAME}" send-keys -t "${SESSION_NAME}":0.0 "exec ${SERVER_START_CMD}" Enter
+		${TMUX_CMD} set -g prefix2 C-a
+		${TMUX_CMD} wait-for -L "command_lock"
+		${TMUX_CMD} pipe-pane -t "${SESSION_NAME}":0.0 "cat > ${GAME_COMMAND_DUMP}"
+		${TMUX_CMD} send-keys -t "${SESSION_NAME}":0.0 "exec ${SERVER_START_CMD}" Enter
 		for ((i=1; i<=MAX_SERVER_START_TIME; i++)); do
 			sleep "${sleep_time:-0.1}"
 			if ! socket_session_is_alive "${SESSION_NAME}"; then
@@ -188,7 +209,7 @@ server_start() {
 				>&2 ${SUDO_CMD} cat "${GAME_COMMAND_DUMP}"
 				${SUDO_CMD} rm -f "${GAME_COMMAND_DUMP}"
 				# Session is dead but remain-on-exit left it open; close it for sure
-				${SUDO_CMD} tmux -L "${SESSION_NAME}" kill-session -t "${SESSION_NAME}"
+				${TMUX_CMD} kill-session -t "${SESSION_NAME}"
 				exit 1
 			elif grep -q -i "${SERVER_START_SUCCESS}" "${GAME_COMMAND_DUMP}"; then
 				echo -e "\e[39;1m done\e[0m"
@@ -198,11 +219,11 @@ server_start() {
 				>&2 echo -e "Server startup has not finished yet; continuing anyways"
 			fi
 		done
-		${SUDO_CMD} tmux -L "${SESSION_NAME}" pipe-pane -t "${SESSION_NAME}":0.0
+		${TMUX_CMD} pipe-pane -t "${SESSION_NAME}":0.0
 		# Let the command buffer be a FIFO pipe
 		${SUDO_CMD} rm -f "${GAME_COMMAND_DUMP}"
 		${SUDO_CMD} mkfifo "${GAME_COMMAND_DUMP}"
-		${SUDO_CMD} tmux -L "${SESSION_NAME}" wait-for -U "command_lock"
+		${TMUX_CMD} wait-for -U "command_lock"
 	fi
 
 	if [[ "${IDLE_SERVER,,}" == "true" ]]; then
@@ -214,19 +235,19 @@ server_start() {
 
 		# Start the idle server daemon
 		if socket_has_session "${IDLE_SESSION_NAME}"; then
-			${SUDO_CMD} tmux -L "${SESSION_NAME}" kill-session -t "${IDLE_SESSION_NAME}"
+			${TMUX_CMD} kill-session -t "${IDLE_SESSION_NAME}"
 			# Restart as soon as the idle_server_daemon has shut down completely
 			for i in {1..100}; do
 				sleep 0.1
 				if ! socket_has_session "${IDLE_SESSION_NAME}"; then
-					${SUDO_CMD} tmux -L "${SESSION_NAME}" new-session -s "${IDLE_SESSION_NAME}" -d "${INAME} idle_server_daemon"
+					${TMUX_CMD} new-session -s "${IDLE_SESSION_NAME}" -d "${INAME} idle_server_daemon"
 					break
 				fi
 				[[ $i -eq 100 ]] && echo -e "An \e[39;1merror\e[0m occurred while trying to reset the idle_server!"
 			done
 		else
 			echo -en "Starting idle server daemon..."
-			${SUDO_CMD} tmux -L "${SESSION_NAME}" new-session -s "${IDLE_SESSION_NAME}" -d "${INAME} idle_server_daemon"
+			${TMUX_CMD} new-session -s "${IDLE_SESSION_NAME}" -d "${INAME} idle_server_daemon"
 			echo -e "\e[39;1m done\e[0m"
 		fi
 	fi
@@ -244,7 +265,7 @@ server_stop() {
 
 		if socket_has_session "${IDLE_SESSION_NAME}"; then
 			echo -en "Stopping idle server daemon..."
-			${SUDO_CMD} tmux -L "${SESSION_NAME}" kill-session -t "${IDLE_SESSION_NAME}"
+			${TMUX_CMD} kill-session -t "${IDLE_SESSION_NAME}"
 			echo -e "\e[39;1m done\e[0m"
 		else
 			echo "The corresponding tmux session for ${IDLE_SESSION_NAME} was already dead."
@@ -449,7 +470,7 @@ server_command() {
 # Enter the tmux game session
 server_console() {
 	if socket_has_session "${SESSION_NAME}"; then
-		${SUDO_CMD} tmux -L "${SESSION_NAME}" attach -t "${SESSION_NAME}":0.0
+		${TMUX_CMD} attach -t "${SESSION_NAME}":0.0
 	else
 		echo "There is no ${SESSION_NAME} session to connect to."
 	fi
@@ -458,19 +479,19 @@ server_console() {
 # Check if there is a session available
 socket_has_session() {
 	if [[ "$(whoami)" != "${GAME_USER}" ]]; then
-		${SUDO_CMD} tmux -L "${SESSION_NAME}" has-session -t "${1}":0.0 2> /dev/null
+		${TMUX_CMD} has-session -t "${1}":0.0 2> /dev/null
 		return $?
 	fi
-	tmux -L "${SESSION_NAME}" has-session -t "${1}":0.0 2> /dev/null
+	${TMUX_CMD} -L "${SESSION_NAME}" has-session -t "${1}":0.0 2> /dev/null
 	return $?
 }
 
 socket_session_is_alive() {
 	if socket_has_session "${1}"; then
 		if [[ "$(whoami)" != "${GAME_USER}" ]]; then
-			return $(${SUDO_CMD} tmux -L "${SESSION_NAME}" list-panes -t "${1}":0.0 -F '#{pane_dead}' 2> /dev/null)
+			return $(${TMUX_CMD} list-panes -t "${1}":0.0 -F '#{pane_dead}' 2> /dev/null)
 		fi
-		return $(tmux -L "${SESSION_NAME}" list-panes -t "${1}":0.0 -F '#{pane_dead}' 2> /dev/null)
+		return $(${TMUX_CMD} list-panes -t "${1}":0.0 -F '#{pane_dead}' 2> /dev/null)
 	else
 		return 1
 	fi
